name: mic_noise_level
description: Plugin for getting noise level using phones microphone.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  permission_handler: ^7.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.klinge.daniels.mic_noise_level
        pluginClass: MicNoiseLevelPlugin
      ios:
        pluginClass: SwiftMicNoiseLevelPlugin
